In [82]:
import numpy as np

In [83]:
row = [1, 2 , 3]
print(type(row))

<class 'list'>


To work wit datas and list, we should convert them to numpy array at first. 
This lets us to use numpy methods for the following array. Also it uses C programming language
which makes the execution faster than before.

In [84]:
nrow = np.array(row)
print(type(nrow))

<class 'numpy.ndarray'>


In [85]:
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

I guess a property is been set on this method (shape) that we can use it without ()

In [86]:
matrix.shape

(3, 3)

Tensor is an matrix that contains matrix in each element

In [87]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[12, 13, 11], [0, 22, 3], [1, 2, 3]],
                   [[14, 33, 54], [23, 11, 7], [13, 90, 8]]])

Changing the shape of numpy array

In [88]:
row = np.array([1, 2, 3])
np.resize(row, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

We can use this method like this too

In [89]:
row.resize((2,2))
print(row)

[[1 2]
 [3 0]]


Creating matrix with only element 1

In [90]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Creating matrix with only element zero

In [91]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
print(row)
np.diag(row)

[[1 2]
 [3 0]]


array([1, 0])

In [93]:
row = np.repeat([1, 2, 3], 3)
row

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [94]:
matrix_1 = np.ones((3,3))
matrix_0 = np.zeros((3,3))

vstack method will put the x on y
[x,y] - > x and y are np arrays
Note : x and y should be placed in a list

In [95]:
np.vstack([matrix_1, matrix_0])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

hstack method will put the y in the right of x
[x,y]

In [96]:
np.hstack([matrix_1, matrix_0])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [97]:
row_1 = np.array([1, 3 , 5, 7, 8, 1, 0])
row_2 = np.array([0, 5 , 2, 1, 11, 5, 0])
row_1 * row_2

array([ 0, 15, 10,  7, 88,  5,  0])

In [98]:
row_1.dot(row_2)

125

In [99]:
matrix = np.array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
matrix.sum()

45

In [101]:
matrix.max()

9

In [102]:
matrix.argmax()

8

In [103]:
matrix.min()

1

In [104]:
matrix.argmin()

0

In [105]:
matrix.mean()

5.0

In [106]:
matrix.std()

2.581988897471611

In [107]:
row = np.arange(11) ** 2
row

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [108]:
row[1:8]

array([ 1,  4,  9, 16, 25, 36, 49])

In [109]:
row[::2]

array([  0,   4,  16,  36,  64, 100])

In [110]:
row[-4:10]

array([49, 64, 81])

In [111]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
matrix[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [113]:
matrix[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [114]:
matrix[matrix < 4]

array([1, 2, 3])

In [115]:
matrix == 4

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [116]:
matrix > 7

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [118]:
matrix[matrix > 5] = 0
matrix

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

Creating np array with random integer numbers between x and y and with shape of n
(x, y, (n))

In [121]:
matrix = np.random.randint(1, 10, (3,3))
matrix

array([[1, 6, 2],
       [4, 5, 7],
       [3, 7, 7]])