In [1]:
import numpy as np

In [2]:
row = [1, 2 , 3]
print(type(row))

<class 'list'>


To work wit datas and list, we should convert them to numpy array at first. 
This lets us to use numpy methods for the following array. Also it uses C programming language
which makes the execution faster than before.

In [3]:
nrow = np.array(row)
print(type(nrow))

<class 'numpy.ndarray'>


In [4]:
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

I guess a property is been set on this method (shape) that we can use it without ()

In [7]:
matrix.shape

(3, 3)

Tensor is an matrix that contains matrix in each element

In [10]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[12, 13, 11], [0, 22, 3], [1, 2, 3]],
                   [[14, 33, 54], [23, 11, 7], [13, 90, 8]]])

Changing the shape of numpy array

In [ ]:
row = np.array([1, 2, 3])
np.resize(row, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

We can use this method like this too

In [21]:
row.resize((2,2))
print(row)

[[1 2]
 [3 0]]


Creating matrix with only element 1

In [25]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Creating matrix with only element zero

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
print(row)
np.diag(row)

[[1 2]
 [3 0]]


array([1, 0])

In [30]:
row = np.repeat([1, 2, 3], 3)
row

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [36]:
matrix_1 = np.ones((3,3))
matrix_0 = np.zeros((3,3))

This method will put the x on y
[x,y] - > x and y are np arrays

In [37]:
np.vstack([matrix_1, matrix_0])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])